queue_rules:
  - name: downstream patches
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - "base ~= ^(main-(delight|xpla|maroo)|release/v0[.][0-9]+[.]x-(delight|xpla|maroo))$"
      - "label = automerge"
      - "-label = kind/upstream-sync"
    merge_conditions:
      - "#approved-reviews-by >= 1"
    merge_method: squash
    commit_message_format:
      title: pr-title
      body: pr-body

  - name: upstream and layer sync
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - "base ~= ^(main-(delight|xpla|maroo)|release/v0[.][0-9]+[.]x-(delight|xpla|maroo))$"
      - "label = automerge"
      - "label = kind/upstream-sync"
    merge_conditions:
      - "#approved-reviews-by >= 1"
    merge_method: merge
    commit_message_format:
      title: pr-title
      body: pr-body

pull_request_rules:
  - name: sync merged main-delight PRs to chain branches
    conditions:
      - "base = main-delight"
      - merged
    actions:
      backport:
        branches:
          - main-xpla
          - main-maroo
        labels:
          - kind/upstream-sync
        title: "{{ title }} (sync #{{ number }} to {{ destination_branch }})"
        body: |
          {{ body }}

          Automatic sync of #{{ number }} from `main-delight` by Mergify.

          {{ cherry_picked_commits }}

  - name: backport shared patches to v0.6.x
    conditions:
      - "base = main-delight"
      - "label = backport/0.6.x"
      - "-label = kind/upstream-sync"
    actions:
      backport:
        branches:
          - release/v0.6.x-delight
        labels:
          - automerge

  - name: backport XPLA patches to v0.6.x
    conditions:
      - "base = main-xpla"
      - "label = backport/0.6.x"
      - "-label = kind/upstream-sync"
    actions:
      backport:
        branches:
          - release/v0.6.x-xpla
        labels:
          - automerge
